In [32]:
import jax.numpy as jnp
import numpy as np
import jax

In [3]:
x = jnp.array([1, 2, 3], dtype=jnp.float32)

Metal device set to: Apple M1 Pro


2023-12-09 13:59:01.062651: W pjrt_plugin/src/mps_client.cc:534] WARNING: JAX Apple GPU support is experimental and not all JAX functionality is correctly supported!


In [4]:
print(x)

[1. 2. 3.]


In [6]:
x.shape

(3,)

In [8]:
# x[2] = 4

In [9]:
x = jnp.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [10]:
x.dtype

dtype('int32')

In [11]:
x[1]

Array([4, 5, 6], dtype=int32)

In [12]:
x[1,2]

Array(6, dtype=int32)

In [13]:
import jax.random as random

In [14]:
key = random.PRNGKey(0)

In [16]:
x = random.uniform(key, shape=[2048, 2048]) - 0.5

In [17]:
x.shape

(2048, 2048)

In [22]:
def my_function(x):
    x = x @ x
    return jnp.maximum(0, x)

In [23]:
y = random.uniform(key, shape=[2, 2])

In [24]:
y

Array([[0.9653214 , 0.22515893],
       [0.63302994, 0.29638183]], dtype=float32)

In [25]:
my_function(y)

Array([[1.0743778 , 0.28408375],
       [0.7986959 , 0.23037453]], dtype=float32)

In [26]:
y @ y

Array([[1.0743778 , 0.28408375],
       [0.7986959 , 0.23037453]], dtype=float32)

In [27]:
y * y

Array([[0.9318454 , 0.05069654],
       [0.4007269 , 0.08784219]], dtype=float32)

In [36]:
%timeit my_function(x).block_until_ready()

9.43 ms ± 111 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [33]:
my_function_jitted = jax.jit(my_function)

In [35]:
%timeit my_function_jitted(x).block_until_ready()

4.86 ms ± 22.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
